import './globals.css';

import type { Metadata } from 'next';
import { Jost } from 'next/font/google';

import NonHyration from '@/components/non-hydration';
import { GlobalProviders } from '@/providers/global-provider';
import { ThemeProvider } from '@/providers/theme-provider';
import WrapperProvider from '@/providers/wrapper-provider';

const jost = Jost({
	variable: "--font-jost",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body suppressHydrationWarning className={`${jost.variable} antialiased`}>
				<NonHyration>
					<ThemeProvider
						attribute="class"
						defaultTheme="light"
						enableSystem
						disableTransitionOnChange
					>
						<GlobalProviders>
							<WrapperProvider>{children}</WrapperProvider>
						</GlobalProviders>
					</ThemeProvider>
				</NonHyration>
			</body>
		</html>
	);
}
